CREATE TABLE `acf_orden_ingreso` (
  `id_ingreso` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `num_ingreso` int(20) DEFAULT NULL,
  `fec_ingreso` date DEFAULT NULL,
  `hor_ingreso` char(7) DEFAULT NULL,
  `detalle` varchar(200) DEFAULT NULL,
  `id_provedor` int(11) DEFAULT NULL,
  `id_tipo_ingreso` int(11) DEFAULT NULL,
  `id_sede` tinyint(4) DEFAULT NULL,
  `val_total` decimal(16,4) DEFAULT NULL,
  `id_usr_crea` int(10) unsigned DEFAULT NULL,
  `fec_creacion` datetime DEFAULT NULL,
  `id_usr_anula` int(10) unsigned DEFAULT NULL,
  `fec_anulacion` datetime DEFAULT NULL,
  `id_usr_cierre` int(10) unsigned DEFAULT NULL,
  `fec_cierre` datetime DEFAULT NULL,
  `estado` tinyint(4) DEFAULT NULL COMMENT '0=Anulado;1=Pendiente;2=Cerrado',
  PRIMARY KEY (`id_ingreso`),
  UNIQUE KEY `NewIndex2acf` (`num_ingreso`),
  KEY `FK_act_orden_ingreso` (`id_provedor`),
  KEY `FK_act_orden_ingreso2` (`id_tipo_ingreso`),
  KEY `FK_act_orden_ingreso3` (`id_usr_crea`),
  KEY `FK_act_orden_ingreso4` (`id_usr_anula`),
  KEY `FK_act_orden_ingreso5` (`id_sede`),
  KEY `FK_act_orden_ingreso7` (`id_usr_cierre`),
  CONSTRAINT `FK_act_orden_ingreso` FOREIGN KEY (`id_provedor`) REFERENCES `tb_terceros` (`id_tercero`),
  CONSTRAINT `FK_act_orden_ingreso2` FOREIGN KEY (`id_tipo_ingreso`) REFERENCES `far_orden_ingreso_tipo` (`id_tipo_ingreso`),
  CONSTRAINT `FK_act_orden_ingreso3` FOREIGN KEY (`id_usr_crea`) REFERENCES `seg_usuarios_sistema` (`id_usuario`),
  CONSTRAINT `FK_act_orden_ingreso4` FOREIGN KEY (`id_usr_anula`) REFERENCES `seg_usuarios_sistema` (`id_usuario`),
  CONSTRAINT `FK_act_orden_ingreso5` FOREIGN KEY (`id_sede`) REFERENCES `tb_sedes` (`id_sede`),
  CONSTRAINT `acf_orden_ingreso_ibfk_1` FOREIGN KEY (`id_usr_cierre`) REFERENCES `seg_usuarios_sistema` (`id_usuario`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8;
