CREATE TABLE `acf_hojavida` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `placa` varchar(40) NOT NULL,
  `serial` varchar(40) NOT NULL,
  `id_marca` int(11) DEFAULT NULL,
  `valor` decimal(16,4) DEFAULT NULL,
  `tipo_activo` int(11) DEFAULT NULL,
  `id_articulo` int(10) DEFAULT NULL,
  `modelo` varchar(45) DEFAULT NULL,
  `id_sede` tinyint(11) DEFAULT NULL,
  `id_area` int(11) DEFAULT NULL,
  `id_proveedor` int(11) DEFAULT NULL,
  `lote` varchar(40) DEFAULT NULL,
  `fecha_fabricacion` date DEFAULT NULL,
  `reg_invima` varchar(45) DEFAULT NULL,
  `fabricante` varchar(80) DEFAULT NULL,
  `lugar_origen` varchar(100) DEFAULT NULL,
  `representante` varchar(100) DEFAULT NULL,
  `dir_representante` varchar(100) DEFAULT NULL,
  `tel_representante` varchar(20) DEFAULT NULL,
  `imagen` varchar(200) DEFAULT NULL,
  `recom_fabricante` varchar(1000) DEFAULT NULL,
  `tipo_adquisicion` int(11) DEFAULT NULL,
  `fecha_adquisicion` date DEFAULT NULL,
  `fecha_instalacion` date DEFAULT NULL,
  `periodo_garantia` varchar(45) DEFAULT NULL,
  `vida_util` varchar(45) DEFAULT NULL,
  `calif_4725` tinyint(10) DEFAULT NULL,
  `calibracion` varchar(100) DEFAULT NULL,
  `vol_min` int(11) DEFAULT NULL,
  `vol_max` int(11) DEFAULT NULL,
  `frec_min` int(11) DEFAULT NULL,
  `frec_max` int(11) DEFAULT NULL,
  `pot_min` int(11) DEFAULT NULL,
  `pot_max` int(11) DEFAULT NULL,
  `cor_min` int(11) DEFAULT NULL,
  `cor_max` int(11) DEFAULT NULL,
  `temp_min` int(11) DEFAULT NULL,
  `temp_max` int(11) DEFAULT NULL,
  `riesgo` int(11) DEFAULT NULL,
  `uso` int(11) DEFAULT NULL,
  `cb_diagnostico` varchar(100) DEFAULT NULL,
  `cb_prevencion` varchar(100) DEFAULT NULL,
  `cb_rehabilitacion` varchar(100) DEFAULT NULL,
  `cb_analisis_lab` varchar(100) DEFAULT NULL,
  `cb_trat_mant` varchar(100) DEFAULT NULL,
  `estado_general` tinyint(10) DEFAULT NULL,
  `causa_est_general` varchar(1000) DEFAULT NULL,
  `fecha_fuera_servicio` date DEFAULT NULL,
  `id_usr_reg` int(10) unsigned DEFAULT NULL,
  `fecha_reg` date DEFAULT NULL,
  `id_usr_act` int(10) unsigned DEFAULT NULL,
  `fecha_act` date DEFAULT NULL,
  `estado` int(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ID_MARCA1_idx` (`id_marca`),
  KEY `FK_ID_ARTICULO1_idx` (`id_articulo`),
  KEY `FK_ID_SEDE_ACF_idx` (`id_sede`),
  KEY `FK_ID_AREA_ACF_idx` (`id_area`),
  KEY `FK_ID_PROVEEDOR_ACF_idx` (`id_proveedor`),
  KEY `FK_ID_TIPO_ADQUISICION_ACF_idx` (`tipo_adquisicion`),
  KEY `FK_ID_USR_REG_ACF_idx` (`id_usr_reg`),
  KEY `FK_ID_USR_ACT_ACF_idx` (`id_usr_act`),
  CONSTRAINT `FK_ID_AREA_ACF` FOREIGN KEY (`id_area`) REFERENCES `far_centrocosto_area` (`id_area`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_ARTICULO1` FOREIGN KEY (`id_articulo`) REFERENCES `far_medicamentos` (`id_med`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_MARCA1` FOREIGN KEY (`id_marca`) REFERENCES `acf_marca` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_PROVEEDOR_ACF` FOREIGN KEY (`id_proveedor`) REFERENCES `tb_terceros` (`id_tercero`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_SEDE_ACF` FOREIGN KEY (`id_sede`) REFERENCES `tb_sedes` (`id_sede`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_TIPO_ADQUISICION_ACF` FOREIGN KEY (`tipo_adquisicion`) REFERENCES `far_orden_ingreso_tipo` (`id_tipo_ingreso`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_USR_ACT_ACF` FOREIGN KEY (`id_usr_act`) REFERENCES `seg_usuarios_sistema` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_USR_REG_ACF` FOREIGN KEY (`id_usr_reg`) REFERENCES `seg_usuarios_sistema` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

CREATE TABLE `acf_hojavida_documentos` (
  `id_documento` int(11) NOT NULL AUTO_INCREMENT,
  `id_activo_fijo` int(10) unsigned DEFAULT NULL,
  `tipo` tinyint(10) DEFAULT NULL,
  `descripcion` varchar(100) DEFAULT NULL,
  `archivo` varchar(200) DEFAULT NULL,
  `id_usuario_crea` int(11) unsigned DEFAULT NULL,
  `fecha_creacion` datetime DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  KEY `FK_ACH_HV_DOC_idx` (`id_activo_fijo`),
  KEY `FK_ACF_HV_USR_idx` (`id_usuario_crea`),
  CONSTRAINT `FK_ACF_HV_DOC` FOREIGN KEY (`id_activo_fijo`) REFERENCES `acf_hojavida` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ACF_HV_USR` FOREIGN KEY (`id_usuario_crea`) REFERENCES `seg_usuarios_sistema` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
